// <auto-generated />
namespace EcomProj.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_new_properties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_new_properties));
        
        string IMigrationMetadata.Id
        {
            get { return "202312152115386_added_new_properties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
